name: wbs-deploy
services:
  wikibase:
    image: wikibase/wikibase:4
    depends_on:
      mysql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-web.entrypoints=web
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-1-web.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-web.service=wikibase-suite-deploy-template-vmvtqn-1-web
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-web.middlewares=redirect-to-https@file
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-websecure.entrypoints=websecure
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-1-websecure.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-websecure.service=wikibase-suite-deploy-template-vmvtqn-1-websecure
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-1-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
      - traefik.http.routers.wikibase-router.rule=Host(`${WIKIBASE_PUBLIC_HOST}`) && !PathPrefix(`/tools`)
    volumes:
      - ../files/config:/config
      - ../files/config/extensions:/var/www/html/extensions/extensions
      - ../files/config/Extensions.php:/var/www/html/LocalSettings.d/90_UserDefinedExtensions.php
      - wikibase-image-data-wikibase-suite-deploy-template-vmvtqn:/var/www/html/images
      - quickstatements-data-wikibase-suite-deploy-template-vmvtqn:/quickstatements/data
    environment:
      MW_ADMIN_NAME: ${MW_ADMIN_NAME}
      MW_ADMIN_PASS: ${MW_ADMIN_PASS}
      MW_ADMIN_EMAIL: ${MW_ADMIN_EMAIL}
      MW_WG_SERVER: https://${WIKIBASE_PUBLIC_HOST}
      DB_SERVER: mysql:3306
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      ELASTICSEARCH_HOST: elasticsearch
      QUICKSTATEMENTS_PUBLIC_URL: https://${WIKIBASE_PUBLIC_HOST}/tools/quickstatements
    healthcheck:
      test: curl --silent --fail localhost/wiki/Main_Page
      interval: 10s
      start_period: 5m
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  wikibase-jobrunner:
    image: wikibase/wikibase:4
    command: /jobrunner-entrypoint.sh
    depends_on:
      wikibase:
        condition: service_healthy
    restart: unless-stopped
    volumes_from:
      - wikibase
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  mysql:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - mysql-data-wikibase-suite-deploy-template-vmvtqn:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      start_period: 1m
      interval: 20s
      timeout: 5s
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  elasticsearch:
    image: wikibase/elasticsearch:1
    restart: unless-stopped
    volumes:
      - elasticsearch-data-wikibase-suite-deploy-template-vmvtqn:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true'
    healthcheck:
      test: curl --silent --fail localhost:9200
      interval: 10s
      start_period: 2m
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  wdqs:
    image: wikibase/wdqs:2
    command: /runBlazegraph.sh
    depends_on:
      wikibase:
        condition: service_healthy
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    volumes:
      - wdqs-data-wikibase-suite-deploy-template-vmvtqn:/wdqs/data
    healthcheck:
      test: curl --silent --fail localhost:9999/bigdata/namespace/wdq/sparql
      interval: 10s
      start_period: 2m
    labels:
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-web.entrypoints=web
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-2-web.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-web.service=wikibase-suite-deploy-template-vmvtqn-2-web
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-web.middlewares=redirect-to-https@file
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-websecure.entrypoints=websecure
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-2-websecure.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-websecure.service=wikibase-suite-deploy-template-vmvtqn-2-websecure
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-2-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
      - traefik.http.routers.wdqs-router.rule=Host(`${WDQS_PUBLIC_HOST}`) && PathPrefix(`/sparql`) && (Method(`GET`) || Method(`OPTIONS`) || Method(`POST`))
      - traefik.http.middlewares.wdqs-prefix.addprefix.prefix=/bigdata/namespace/wdq/
      - traefik.http.middlewares.wdqs-headers.headers.accesscontrolallowmethods=GET,OPTIONS,POST
      - traefik.http.middlewares.wdqs-headers.headers.customresponseheaders.VARY=Accept
      - traefik.http.middlewares.wdqs-headers.headers.customrequestheaders.X-BIGDATA-READ-ONLY=yes
      - traefik.http.middlewares.wdqs-headers.headers.customrequestheaders.X-BIGDATA-MAX-QUERY-MILLIS=300000
      - traefik.http.middlewares.wdqs-cors-headers.headers.accesscontrolallowheaders=*
      - traefik.http.middlewares.wdqs-rate-limit.ratelimit.burst=30
      - traefik.http.middlewares.wdqs-rate-limit.ratelimit.average=60
      - traefik.http.middlewares.wdqs-rate-limit.ratelimit.period=1m
      - traefik.http.routers.wdqs-router.middlewares=wdqs-prefix,wdqs-headers,wdqs-cors-headers,wdqs-rate-limit
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  wdqs-updater:
    image: wikibase/wdqs:2
    command: /runUpdate.sh
    depends_on:
      wdqs:
        condition: service_healthy
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    environment:
      WIKIBASE_CONCEPT_URI: https://${WIKIBASE_PUBLIC_HOST}
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  wdqs-frontend:
    image: wikibase/wdqs-frontend:2
    restart: unless-stopped
    volumes:
      - ../files/config:/config
    labels:
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-web.entrypoints=web
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-3-web.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-web.service=wikibase-suite-deploy-template-vmvtqn-3-web
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-web.middlewares=redirect-to-https@file
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-websecure.entrypoints=websecure
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-3-websecure.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-websecure.service=wikibase-suite-deploy-template-vmvtqn-3-websecure
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-3-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
      - traefik.http.routers.wdqs-frontend-router.rule=Host(`${WDQS_PUBLIC_HOST}`) && !PathPrefix(`/sparql`)
    environment:
      WDQS_PUBLIC_URL: https://${WDQS_PUBLIC_HOST}/sparql
      WIKIBASE_PUBLIC_URL: https://${WIKIBASE_PUBLIC_HOST}/w/api.php
    healthcheck:
      test: curl --silent --fail localhost
      interval: 10s
      start_period: 2m
    networks:
      - wikibase-suite-deploy-template-vmvtqn
  quickstatements:
    image: wikibase/quickstatements:1
    depends_on:
      wikibase:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - quickstatements-data-wikibase-suite-deploy-template-vmvtqn:/quickstatements/data
    labels:
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-web.entrypoints=web
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-4-web.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-web.service=wikibase-suite-deploy-template-vmvtqn-4-web
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-web.middlewares=redirect-to-https@file
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-websecure.entrypoints=websecure
      - traefik.http.services.wikibase-suite-deploy-template-vmvtqn-4-websecure.loadbalancer.server.port=80
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-websecure.service=wikibase-suite-deploy-template-vmvtqn-4-websecure
      - traefik.http.routers.wikibase-suite-deploy-template-vmvtqn-4-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
      - traefik.http.routers.quickstatements-router.rule=Host(`${WIKIBASE_PUBLIC_HOST}`) && PathPrefix(`/tools/quickstatements`)
      - traefik.http.middlewares.quickstatements-redirectregex.redirectregex.regex=/tools/quickstatements$
      - traefik.http.middlewares.quickstatements-redirectregex.redirectregex.replacement=/tools/quickstatements/
      - traefik.http.middlewares.quickstatements-redirectregex.redirectregex.permanent=true
      - traefik.http.middlewares.quickstatements-stripprefix.stripprefix.prefixes=/tools/quickstatements
      - traefik.http.routers.quickstatements-router.middlewares=quickstatements-redirectregex,quickstatements-stripprefix
    environment:
      QUICKSTATEMENTS_PUBLIC_URL: https://${WIKIBASE_PUBLIC_HOST}/tools/quickstatements
      WIKIBASE_PUBLIC_URL: https://${WIKIBASE_PUBLIC_HOST}
    healthcheck:
      test: curl --silent --fail localhost
      interval: 10s
      start_period: 2m
    networks:
      - wikibase-suite-deploy-template-vmvtqn
volumes:
  wikibase-image-data-wikibase-suite-deploy-template-vmvtqn: null
  mysql-data-wikibase-suite-deploy-template-vmvtqn: null
  wdqs-data-wikibase-suite-deploy-template-vmvtqn: null
  elasticsearch-data-wikibase-suite-deploy-template-vmvtqn: null
  quickstatements-data-wikibase-suite-deploy-template-vmvtqn: null
networks:
  wikibase-suite-deploy-template-vmvtqn:
    name: wikibase-suite-deploy-template-vmvtqn
    external: true
