[variables]
WIKIBASE_PUBLIC_HOST = "wikibase.example"
WDQS_PUBLIC_HOST = "query.wikibase.example"
MW_ADMIN_NAME = "admin"
MW_ADMIN_EMAIL = "admin@wikibase.example"
MW_ADMIN_PASS = "change-this-password"
DB_NAME = "my_wiki"
DB_USER = "sqluser"
DB_PASS = "change-this-password"

[config]

[config.env]
WIKIBASE_PUBLIC_HOST = "${WIKIBASE_PUBLIC_HOST}"
WDQS_PUBLIC_HOST = "${WDQS_PUBLIC_HOST}"
MW_ADMIN_NAME = "${MW_ADMIN_NAME}"
MW_ADMIN_EMAIL = "${MW_ADMIN_EMAIL}"
MW_ADMIN_PASS = "${MW_ADMIN_EMAIL}"
DB_NAME = "${DB_NAME"
DB_USER = "${DB_USER}"
DB_PASS = "${DB_PASS}"

[[config.domains]]
serviceName = "wikibase"
port = 80
host = "${WIKIBASE_PUBLIC_HOST}"
path = "/"

[[config.domains]]
serviceName = "wdqs"
port = 80
host = "${WDQS_PUBLIC_HOST}"
path = "/sparql"

[[config.domains]]
serviceName = "wdqs-frontend"
port = 80
host = "${WDQS_PUBLIC_HOST}"

[[config.domains]]
serviceName = "wdqs-frontend"
port = 80
host = "${WDQS_PUBLIC_HOST}"
path = 'tools/quickstatements'

[[config.mounts]]
filePath = "/config/wikibase-php.ini"
content = """
; ##############################################################################
; Wikibase Suite PHP settings
; ##############################################################################
; Feel free to adjust those settings according your needs.
; Changes will be picked up automatically by the wikibase container on restart.

; Set the PHP upload limits be the same as the MediaWiki default of 100M.
; Should match the wgMaxUploadSize setting in LocalSettings.php
file_uploads = On
upload_max_filesize = 100M
post_max_size = 100M

; Set the PHP memory and execution limits
memory_limit = 100M
max_execution_time = 600
"""

[[config.mounts]]
filePath = "/config/extensions/Extensions.php"
content = """
<?php
// ************************************************************************
// Wikibase Suite Deploy Extension.php
// ************************************************************************
//
// File to load MediaWiki extension.
//
// This file will be loaded after all other extensions have been loaded,
// just like as if this code would be at the end of LocalSettings.php.
//
// Make sure to prefix the extensions name with "extensions/" when loading.
// e.g. when extension installation instructions state you need to put
//   wfLoadExtension( 'WikibaseLexeme' );
// here in Wikibase Suite Deploy you need to put
//   wfLoadExtension( 'extensions/WikibaseLexeme' );
"""
