services:
  # --------------------------------------------------
  # C. REVERSE PROXY
  # --------------------------------------------------

  nginx:
    image: wikibase/deploy-reverse-proxy
    build:
      context: ./deploy-reverse-proxy
    depends_on:
      - quickstatements
      - wikibase
      - wdqs-frontend
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${WIKIBASE_PUBLIC_HOST}
      EMAIL: ${MW_ADMIN_EMAIL}
    volumes:
      - ./certs:/certs:z
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
