#cloud-config

package_update: true
package_upgrade: true

packages:
  - git

runcmd:
  - bash -c "$(curl -fsSL https://raw.githubusercontent.com/wmde/wikibase-release-pipeline/refs/heads/deploy-setup-script/deploy/setup/setup.sh)" -- --cloud-init --verbose
